### PR TITLE
Add the possibility install core plugins

### PR DESCRIPTION
**Pull request by stamak**
Gerrit war file has packaged core plugins [1] which can be easily installed.
For example to install plugins replication and download-commands below
pillars should be added:

`core_plugins:`
`- replication`
`- download-commands`

[1] https://gerrit-review.googlesource.com/Documentation/config-plugins.html#core-plugins

### CODE REVIEW

**Comment by envintus** [comment]
@stamak Any chance you could rebase and I'll merge the pull request?

**Comment by stamak** [comment]
@envintus done

**Comment by envintus** [comment]
@stamak Awesome, thanks for contributing!

**Comment by stamak** [comment]
not at all ;)
@envintus thx you too

**Pull request merged**
